# Generated by Django 2.0 on 2018-01-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180112_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Price')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Coin')),
            ],
        ),
    ]
