# Generated by Django 2.0 on 2018-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coin_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='code',
            field=models.CharField(default='NAN', max_length=10),
        ),
        migrations.AddField(
            model_name='coin',
            name='logo',
            field=models.ImageField(default='Nix', height_field=256, upload_to='uploads/', width_field=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
    ]
