# Generated by Django 2.0 on 2018-01-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180103_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='logo',
        ),
    ]
