# Generated by Django 2.0 on 2018-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180112_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
