
# Generated by Django 2.0 on 2018-01-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_coin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='logo',
            field=models.ImageField(default='NAN', height_field=256, upload_to='uploads/', width_field=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
