# Generated by Django 2.0 on 2018-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180115_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Logo'),
        ),
    ]
