# Generated by Django 2.0 on 2018-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180103_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='owner',
        ),
        migrations.AlterField(
            model_name='coin',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
    ]
