# Generated by Django 2.0 on 2018-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180115_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
