# Generated by Django 2.0 on 2018-01-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_coin_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='wallet',
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
