# Generated by Django 2.0 on 2018-01-15 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180115_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
    ]
