# Generated by Django 2.0 on 2018-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180103_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits='8', verbose_name='Price'),
        ),
    ]
