# Generated by Django 2.0 on 2018-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180103_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=16, verbose_name='Price'),
        ),
    ]
