# Generated by Django 2.0 on 2018-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180103_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='published_date',
            field=models.DateTimeField(verbose_name='Create date'),
        ),
    ]
