# Generated by Django 2.0 on 2018-01-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180104_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
    ]
