# Generated by Django 2.0 on 2018-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='balance',
        ),
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Value'),
        ),
    ]
