# Generated by Django 2.0 on 2018-01-07 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20180105_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('Mobile', 'Mobile'), ('Web', 'Web'), ('Desktop', 'Desktop')], default='Desktop', max_length=16, verbose_name='Device')),
                ('info', models.TextField(verbose_name='Info')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='asset',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Wallet'),
            preserve_default=False,
        ),
    ]
