# Generated by Django 2.0 on 2018-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180107_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
